GET http://localhost:3200/notes
content-type: application/json

####
POST http://localhost:3200/notes
content-type: application/json

{
    "title": "React Interview  2nd",
    "content": "NAB",
    "created_at": "12/12/2023"
}

####
GET http://localhost:3200/notes/1
content-type: application/json

####
PATCH http://localhost:3200/notes/1
content-type: application/json

{
    "title": "Updated Grocery List",
    "content": "Grocery List",
    "created_at": "12/12/2023"
}
####
DELETE http://localhost:3200/notes/86e8
content-type: application/json